name=ESP32TinyUSB-extended-usb-host
version=1.0.0
author=Gershy13 
maintainer=Gershy13
sentence=Extended USB host functions for ESP32-S2
paragraph=This library provides an implementation of tinyusb for the ESP32-S2 for Arduino. Added extra usb host functioanlity 
category=Communication
architectures=esp32
includes=
depends=
url=https://github.com/Gershy13/ESP32TinyUSB-extended-usb-host
